# Generated by Django 4.2.6 on 2023-10-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_aluno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('RG', models.IntegerField()),
                ('cpf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_da_turma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('M', 'MANHA'), ('T', 'TARDE'), ('N', 'NOITE'), ('I', 'INTEGRAL')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_de_nascimento', models.DateField()),
                ('RG', models.IntegerField()),
                ('CPF', models.IntegerField()),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('codigo_do_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apkchamada.codigoaluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apkchamada.turma')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apkchamada.turnos')),
            ],
        ),
    ]
